### ISSUE TITLE
pypi sdist cannot be compiled automatically by pip

### ISSUE THREAD

**Issue by alyssadev** [jamesturk/jellyfish#195]
Hi, I'm using an armv7 system, so there are no compatible wheels to be downloaded at this time. pip3 attempted to download and install the sdist but failed as below:

```
Collecting jellyfish (from beets)
  Using cached https://files.pythonhosted.org/packages/8e/14/d72e01b3e3d5d9f1f5f12c8afafda88f068385c612d8aa517df2b88e2059/jellyfish-1.0.0.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-v4bvtx8g/jellyfish/setup.py'
```

~~A setup.py that calls cargo to build the Rust implementations used in 1.0.0 would be neat~~

oh i see the wheels are generated with `maturin`, interesting, hadn't heard of this before

**Comment by jamesturk** [comment]
Hi-- Part of the issue is that you're on 3.7 which hit EOL earlier this year.  I'm going to see if I can get arm7 builds added though.

**Comment by jamesturk** [comment]
If you can access Python 3.8 or later, this issue may be resolved, let me know if you're able to test!

**Comment by alyssadev** [comment]
Had to clear my pip cache so it stopped trying to install the sdist, but this works now, thanks!

```
$ pip3 install jellyfish
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting jellyfish
  Obtaining dependency information for jellyfish from https://files.pythonhosted.org/packages/23/f1/e7d6d984f1e24b8502a7f2c0ed7db9c60b011bd5f1537b7778905375247d/jellyfish-1.0.1-cp310-cp310-manylinux_2_17_armv7l.manylinux2014_armv7l.whl.metadata
  Downloading jellyfish-1.0.1-cp310-cp310-manylinux_2_17_armv7l.manylinux2014_armv7l.whl.metadata (2.5 kB)
Downloading jellyfish-1.0.1-cp310-cp310-manylinux_2_17_armv7l.manylinux2014_armv7l.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 5.2 MB/s eta 0:00:00
Installing collected packages: jellyfish
Successfully installed jellyfish-1.0.1
```
